AllCops:
  GrapeDir: 'app/api'

Grape/FieldName:
  EnforcedStyle: snake_case
  SupportedStyles:
    - snake_case
    - camelCase

Grape/RouteParamType:
  Enabled: true
  Safe: false
  VersionAdded: '0.1'

Grape/ParamsPosition:
  Enabled: true
  Safe: false
  VersionAdded: '0.1'
